import { Router } from "express";
import adminRoutes from "../modules/admin/admin.routes.js";
import alertsRoutes from "../modules/alerts/alerts.routes.js";
import analyticsRoutes from "../modules/analytics/analytics.routes.js";
import appointmentsRoutes from "../modules/appointments/appointments.routes.js";
import authRoutes from "../modules/auth/auth.routes.js";
import chatRoutes from "../modules/chat/chat.routes.js";
import consultationsRoutes from "../modules/consultations/consultations.routes.js";
import dashboardRoutes from "../modules/dashboard/dashboard.routes.js";
import doctorsRoutes from "../modules/doctors/doctors.routes.js";
import followUpsRoutes from "../modules/follow-ups/followUps.routes.js";
import groupsRoutes from "../modules/groups/groups.routes.js";
import medicalRecordsRoutes from "../modules/medical-records/medicalRecords.routes.js";
import medicationsRoutes from "../modules/medications/medications.routes.js";
import notificationsRoutes from "../modules/notifications/notifications.routes.js";
import patientsRoutes from "../modules/patients/patients.routes.js";
import presenceRoutes from "../modules/presence/presence.routes.js";
import postsRoutes from "../modules/posts/posts.routes.js";
import reviewsRoutes from "../modules/reviews/reviews.routes.js";
import symptomsRoutes from "../modules/symptoms/symptoms.routes.js";
import treatmentPlansRoutes from "../modules/treatment-plans/treatmentPlans.routes.js";
import uploadsRoutes from "../modules/uploads/uploads.routes.js";
import usersRoutes from "../modules/users/users.routes.js";

const router = Router();

router.use("/auth", authRoutes);
router.use("/users", usersRoutes);
router.use("/doctors", doctorsRoutes);
router.use("/patients", patientsRoutes);
router.use("/posts", postsRoutes);
router.use("/consultations", consultationsRoutes);
router.use("/appointments", appointmentsRoutes);
router.use("/treatment-plans", treatmentPlansRoutes);
router.use("/medications", medicationsRoutes);
router.use("/follow-ups", followUpsRoutes);
router.use("/medical-records", medicalRecordsRoutes);
router.use("/reviews", reviewsRoutes);
router.use("/symptoms", symptomsRoutes);
router.use("/notifications", notificationsRoutes);
router.use("/presence", presenceRoutes);
router.use("/uploads", uploadsRoutes);
router.use("/groups", groupsRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/admin", adminRoutes);
router.use("/admin/analytics", analyticsRoutes);
router.use("/admin/alerts", alertsRoutes);
router.use("/", chatRoutes);

export default router;
