const translations = {
  "Something went wrong": "حدث خطأ غير متوقع.",
  "Invalid credentials": "بيانات الدخول غير صحيحة.",
  "Login failed": "فشل تسجيل الدخول.",
  "Registration failed": "فشل إنشاء الحساب.",
  "Email is already registered": "البريد الإلكتروني مستخدم بالفعل.",
  "Doctor account is not approved yet": "حساب الطبيب لم تتم الموافقة عليه بعد.",
  "Your account is pending approval": "حسابك ما زال بانتظار الموافقة.",
  "Your account was rejected or disabled": "تم رفض الحساب أو تعطيله.",
  "Failed to fetch posts": "تعذر جلب المنشورات الطبية.",
  "Failed to load consultations": "تعذر تحميل الاستشارات.",
  "Failed to create consultation": "تعذر إنشاء طلب الاستشارة.",
  "Failed to respond": "تعذر إرسال الرد.",
  "Failed to update status": "تعذر تحديث الحالة.",
  "Failed to load appointments": "تعذر تحميل المواعيد.",
  "Failed to book appointment": "تعذر حجز الموعد.",
  "Failed to load admin data": "تعذر تحميل بيانات الإدارة.",
  "Failed to load doctor posts": "تعذر تحميل منشورات الطبيب.",
  "Failed to save post": "تعذر حفظ المنشور.",
  "Failed to delete post": "تعذر حذف المنشور.",
  "Failed to load clinical sources.": "تعذر تحميل بيانات المرضى والاستشارات.",
  "Failed to create treatment plan.": "تعذر إنشاء الخطة العلاجية.",
  "Failed to load treatment plan.": "تعذر تحميل الخطة العلاجية.",
  "Failed to update treatment plan.": "تعذر تحديث الخطة العلاجية.",
  "Failed to load follow-ups.": "تعذر تحميل المتابعات.",
  "Failed to save professional note.": "تعذر حفظ الملاحظة المهنية.",
  "Failed to load reviews.": "تعذر تحميل التقييمات.",
  "Failed to submit review.": "تعذر إرسال التقييم.",
  "Failed to load groups.": "تعذر تحميل المجموعات.",
  "Failed to join group.": "تعذر الانضمام إلى المجموعة.",
  "Failed to load group.": "تعذر تحميل المجموعة.",
  "Failed to update group.": "تعذر تحديث المجموعة.",
  "Failed to save group post.": "تعذر حفظ منشور المجموعة.",
  "Failed to load notifications.": "تعذر تحميل الإشعارات.",
  "Failed to update notification.": "تعذر تحديث الإشعار.",
  "Failed to update notifications.": "تعذر تحديث الإشعارات.",
  "Failed to load medical record.": "تعذر تحميل السجل الطبي.",
  "Failed to update medical record.": "تعذر تحديث السجل الطبي.",
  "Failed to submit follow-up.": "تعذر إرسال المتابعة.",
  "Failed to create group.": "تعذر إنشاء المجموعة.",
  "Failed to load analytics.": "تعذر تحميل التحليلات.",
  "Doctor profile not found": "تعذر العثور على ملف الطبيب.",
  "Patient profile not found": "تعذر العثور على ملف المريض.",
  "Patient account is not active": "حساب المريض غير نشط.",
  "Consultation not found": "تعذر العثور على الاستشارة.",
  "Consultation does not belong to this doctor and patient": "هذه الاستشارة لا تخص هذا الطبيب وهذا المريض.",
  "Treatment plans can only be linked to accepted or completed consultations": "لا يمكن ربط الخطة العلاجية إلا باستشارة مقبولة أو مكتملة.",
  "Doctor can only create treatment plans for assigned patients": "يمكن للطبيب إنشاء خطط علاجية للمرضى المرتبطين به فقط.",
  "Treatment plan not found": "تعذر العثور على الخطة العلاجية.",
  "You can only update your own treatment plans": "يمكنك تحديث خططك العلاجية فقط.",
  "You can only access your own treatment plans": "يمكنك الوصول إلى خططك العلاجية فقط.",
  "Invalid treatment plan status": "حالة الخطة العلاجية غير صالحة.",
  "End date must be on or after start date": "يجب أن يكون تاريخ النهاية في نفس يوم البداية أو بعده.",
  "You can only submit follow-ups for your own treatment plans": "يمكنك إرسال المتابعة لخططك العلاجية فقط.",
  "Follow-ups can only be submitted for active treatment plans": "يمكن إرسال المتابعات للخطط العلاجية النشطة فقط.",
  "Follow-up entry not found": "تعذر العثور على سجل المتابعة.",
  "You can only annotate follow-ups for your own patients": "يمكنك إضافة ملاحظات لمتابعات مرضاك فقط.",
  "Group not found": "تعذر العثور على المجموعة.",
  "You can only access public groups or groups you have joined": "يمكنك الوصول إلى المجموعات العامة أو المجموعات التي انضممت إليها فقط.",
  "You can only access groups you created": "يمكنك الوصول إلى المجموعات التي أنشأتها فقط.",
  "You can only update your own groups": "يمكنك تحديث مجموعاتك فقط.",
  "Only the group owner can publish posts": "يمكن لمالك المجموعة فقط نشر المنشورات.",
  "Only the group owner can update group posts": "يمكن لمالك المجموعة فقط تحديث منشورات المجموعة.",
  "At least one treatment plan field is required": "يجب إدخال حقل واحد على الأقل للخطة العلاجية.",
  "At least one medication field is required": "يجب إدخال حقل واحد على الأقل للدواء.",
  "At least one group field is required": "يجب إدخال حقل واحد على الأقل للمجموعة.",
  "At least one post field is required": "يجب إدخال حقل واحد على الأقل للمنشور.",
  "Provide exactly one completed consultation or appointment": "يجب تحديد استشارة مكتملة واحدة أو موعد مكتمل واحد فقط.",
  "Notification not found": "تعذر العثور على الإشعار."
};

export function getErrorMessage(error, fallback = "حدث خطأ غير متوقع.") {
  const message = error?.response?.data?.message || fallback;
  return translations[message] || message || fallback;
}
